"""add risk model

Revision ID: 041a93448928
Revises: 0d59b40252cc
Create Date: 2026-04-24 13:48:38.433606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041a93448928'
down_revision: Union[str, Sequence[str], None] = '0d59b40252cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('clause_id', sa.Integer(), nullable=True),
    sa.Column('risk_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('source_snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_clause_id'), 'risks', ['clause_id'], unique=False)
    op.create_index(op.f('ix_risks_contract_id'), 'risks', ['contract_id'], unique=False)
    op.create_index(op.f('ix_risks_id'), 'risks', ['id'], unique=False)
    op.create_index(op.f('ix_risks_risk_type'), 'risks', ['risk_type'], unique=False)
    op.create_index(op.f('ix_risks_severity'), 'risks', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risks_severity'), table_name='risks')
    op.drop_index(op.f('ix_risks_risk_type'), table_name='risks')
    op.drop_index(op.f('ix_risks_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_contract_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_clause_id'), table_name='risks')
    op.drop_table('risks')
    # ### end Alembic commands ###
