"""update contract model

Revision ID: 76ab894736e5
Revises: fa6ef8c5f042
Create Date: 2026-04-06 20:05:59.669954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ab894736e5'
down_revision: Union[str, Sequence[str], None] = 'fa6ef8c5f042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('contracts', sa.Column('is_indexed', sa.Boolean(), nullable=False))
    op.add_column('contracts', sa.Column('embedding_status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'embedding_status')
    op.drop_column('contracts', 'is_indexed')
    op.drop_column('contracts', 'processing_error')
    # ### end Alembic commands ###
