"""update contract metadata fields

Revision ID: fa6ef8c5f042
Revises: 6a35de40ace7
Create Date: 2026-04-03 16:57:37.353706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6ef8c5f042'
down_revision: Union[str, Sequence[str], None] = '6a35de40ace7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('contracts', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('contracts', sa.Column('file_type', sa.String(length=50), nullable=True))
    op.add_column('contracts', sa.Column('ocr_used', sa.Boolean(), nullable=False))
    op.add_column('contracts', sa.Column('parse_method', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_unique_constraint(None, 'contracts', ['file_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='unique')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_column('contracts', 'parse_method')
    op.drop_column('contracts', 'ocr_used')
    op.drop_column('contracts', 'file_type')
    op.drop_column('contracts', 'file_path')
    op.drop_column('contracts', 'file_name')
    # ### end Alembic commands ###
