"""update contract model

Revision ID: 5001cd84f863
Revises: 76ab894736e5
Create Date: 2026-04-06 20:11:32.961779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5001cd84f863'
down_revision: Union[str, Sequence[str], None] = '76ab894736e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('cleaned_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'cleaned_text')
    # ### end Alembic commands ###
