"""add email verification fields to users

Revision ID: 6a35de40ace7
Revises: 36873ef1517e
Create Date: 2026-04-01 13:59:25.455681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a35de40ace7'
down_revision: Union[str, Sequence[str], None] = "d2ae36960eb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('contracts', sa.Column('effective_date', sa.Date(), nullable=True))
    op.add_column('contracts', sa.Column('expiration_date', sa.Date(), nullable=True))
    op.add_column('contracts', sa.Column('notice_period_days', sa.Integer(), nullable=True))
    op.drop_column('contracts', 'raw_text')
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('code_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'code_expires_at')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'is_verified')
    op.add_column('contracts', sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('contracts', 'notice_period_days')
    op.drop_column('contracts', 'expiration_date')
    op.drop_column('contracts', 'effective_date')
    op.drop_column('contracts', 'extracted_text')
    # ### end Alembic commands ###
