"""update contract model for week 5 and 6

Revision ID: a2358b1fa19d
Revises: 5001cd84f863
Create Date: 2026-04-20 14:23:22.124898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2358b1fa19d'
down_revision: Union[str, Sequence[str], None] = '5001cd84f863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('extracted_metadata_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'extracted_metadata_json')
    # ### end Alembic commands ###
