"""add summary obligation and alert models

Revision ID: a56212674101
Revises: 041a93448928
Create Date: 2026-04-24 16:25:50.134566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56212674101'
down_revision: Union[str, Sequence[str], None] = '041a93448928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('summary_type', sa.String(length=50), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_contract_id'), 'summaries', ['contract_id'], unique=False)
    op.create_index(op.f('ix_summaries_id'), 'summaries', ['id'], unique=False)
    op.create_table('obligations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('clause_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('reminder_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligations_clause_id'), 'obligations', ['clause_id'], unique=False)
    op.create_index(op.f('ix_obligations_contract_id'), 'obligations', ['contract_id'], unique=False)
    op.create_index(op.f('ix_obligations_id'), 'obligations', ['id'], unique=False)
    op.create_index(op.f('ix_obligations_status'), 'obligations', ['status'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('obligation_id', sa.Integer(), nullable=True),
    sa.Column('risk_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('trigger_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('send_email', sa.Boolean(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_contract_id'), 'alerts', ['contract_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_obligation_id'), 'alerts', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_alerts_risk_id'), 'alerts', ['risk_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_clauses_contract_id'), 'clauses', ['contract_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clauses_contract_id'), table_name='clauses')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_risk_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_obligation_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_contract_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_obligations_status'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_id'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_contract_id'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_clause_id'), table_name='obligations')
    op.drop_table('obligations')
    op.drop_index(op.f('ix_summaries_id'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_contract_id'), table_name='summaries')
    op.drop_table('summaries')
    # ### end Alembic commands ###
