UPLOAD_DIR = "uploads"
SUPPORTED_FILE_TYPES = (".pdf", ".docx")


DEFAULT_CHUNK_SIZE = 500


MIN_TEXT_LENGTH = 10 


MAX_FILE_SIZE_MB = 10  

CONTRACT_STATUS_UPLOADED = "uploaded"
CONTRACT_STATUS_PROCESSING = "processing"
CONTRACT_STATUS_OCR_PROCESSING = "ocr_processing"
CONTRACT_STATUS_PARSED = "parsed"
CONTRACT_STATUS_INDEXING = "indexing"
CONTRACT_STATUS_ANALYSIS_PENDING = "analysis_pending"
CONTRACT_STATUS_COMPLETED = "completed"
CONTRACT_STATUS_FAILED = "failed"

CONTRACT_STATUSES = [
    CONTRACT_STATUS_UPLOADED,
    CONTRACT_STATUS_PROCESSING,
    CONTRACT_STATUS_OCR_PROCESSING,
    CONTRACT_STATUS_PARSED,
    CONTRACT_STATUS_INDEXING,
    CONTRACT_STATUS_ANALYSIS_PENDING,
    CONTRACT_STATUS_COMPLETED,
    CONTRACT_STATUS_FAILED,
]

EMBEDDING_STATUS_PENDING = "pending"
EMBEDDING_STATUS_PROCESSING = "processing"
EMBEDDING_STATUS_COMPLETED = "completed"
EMBEDDING_STATUS_FAILED = "failed"

EMBEDDING_STATUSES = [
    EMBEDDING_STATUS_PENDING,
    EMBEDDING_STATUS_PROCESSING,
    EMBEDDING_STATUS_COMPLETED,
    EMBEDDING_STATUS_FAILED,
]