UPLOAD_DIR = "uploads"
SUPPORTED_FILE_TYPES = (".pdf", ".docx")


DEFAULT_CHUNK_SIZE = 500


MIN_TEXT_LENGTH = 10 


MAX_FILE_SIZE_MB = 10  

CONTRACT_STATUS_UPLOADED = "uploaded"
CONTRACT_STATUS_PROCESSING = "processing"
CONTRACT_STATUS_OCR_PROCESSING = "ocr_processing"
CONTRACT_STATUS_PARSED = "parsed"
CONTRACT_STATUS_INDEXING = "indexing"
CONTRACT_STATUS_ANALYSIS_PENDING = "analysis_pending"
CONTRACT_STATUS_COMPLETED = "completed"
CONTRACT_STATUS_FAILED = "failed"
CONTRACT_STATUS_ANALYSIS_FAILED = "analysis_failed"

CONTRACT_STATUSES = [
    CONTRACT_STATUS_UPLOADED,
    CONTRACT_STATUS_PROCESSING,
    CONTRACT_STATUS_OCR_PROCESSING,
    CONTRACT_STATUS_PARSED,
    CONTRACT_STATUS_INDEXING,
    CONTRACT_STATUS_ANALYSIS_PENDING,
    CONTRACT_STATUS_COMPLETED,
    CONTRACT_STATUS_FAILED,
    CONTRACT_STATUS_ANALYSIS_FAILED,
]

EMBEDDING_STATUS_PENDING = "pending"
EMBEDDING_STATUS_PROCESSING = "processing"
EMBEDDING_STATUS_COMPLETED = "completed"
EMBEDDING_STATUS_FAILED = "failed"

EMBEDDING_STATUSES = [
    EMBEDDING_STATUS_PENDING,
    EMBEDDING_STATUS_PROCESSING,
    EMBEDDING_STATUS_COMPLETED,
    EMBEDDING_STATUS_FAILED,
]
RISK_SEVERITY_LOW = "low"
RISK_SEVERITY_MEDIUM = "medium"
RISK_SEVERITY_HIGH = "high"

RISK_SEVERITIES = [
    RISK_SEVERITY_LOW,
    RISK_SEVERITY_MEDIUM,
    RISK_SEVERITY_HIGH,
]

RISK_TYPE_LIABILITY = "liability"
RISK_TYPE_PAYMENT = "payment"
RISK_TYPE_TERMINATION = "termination"
RISK_TYPE_CONFIDENTIALITY = "confidentiality"
RISK_TYPE_RENEWAL = "renewal"
RISK_TYPE_COMPLIANCE = "compliance"

RISK_TYPES = [
    RISK_TYPE_LIABILITY,
    RISK_TYPE_PAYMENT,
    RISK_TYPE_TERMINATION,
    RISK_TYPE_CONFIDENTIALITY,
    RISK_TYPE_RENEWAL,
    RISK_TYPE_COMPLIANCE,
]
OBLIGATION_STATUS_PENDING = "pending"
OBLIGATION_STATUS_COMPLETED = "completed"
OBLIGATION_STATUS_OVERDUE = "overdue"

OBLIGATION_STATUSES = [
    OBLIGATION_STATUS_PENDING,
    OBLIGATION_STATUS_COMPLETED,
    OBLIGATION_STATUS_OVERDUE,
]

ALERT_TYPE_EXPIRING_SOON = "expiring_soon"
ALERT_TYPE_RENEWAL_UPCOMING = "renewal_upcoming"
ALERT_TYPE_DUE_SOON = "due_soon"
ALERT_TYPE_OVERDUE = "overdue"
ALERT_TYPE_HIGH_RISK = "high_risk"

ALERT_TYPES = [
    ALERT_TYPE_EXPIRING_SOON,
    ALERT_TYPE_RENEWAL_UPCOMING,
    ALERT_TYPE_DUE_SOON,
    ALERT_TYPE_OVERDUE,
    ALERT_TYPE_HIGH_RISK,
]

ALERT_STATUS_UNREAD = "unread"
ALERT_STATUS_READ = "read"

ALERT_STATUSES = [
    ALERT_STATUS_UNREAD,
    ALERT_STATUS_READ,
]

POLICY_SEVERITY_LOW = "low"
POLICY_SEVERITY_MEDIUM = "medium"
POLICY_SEVERITY_HIGH = "high"

POLICY_SEVERITIES = [
    POLICY_SEVERITY_LOW,
    POLICY_SEVERITY_MEDIUM,
    POLICY_SEVERITY_HIGH,
]